### ISSUE TITLE
Exposing the clear method from the UpdateManager

### ISSUE THREAD

**Issue by cenk1cenk2** [keindev/stdout-update#550]
Hello @keindev,

Thank you for this well-organized library, is it possible/do you find it reasonable to expose the `clear` method, so that we can clear the output from outside, because with `update` method checks the length of the array so that we can not pass an empty array.

**Comment by keindev** [comment]
> Hello @keindev,
> 
> Thank you for this well-organized library, is it possible/do you find it reasonable to expose the `clear` method, so that we can clear the output from outside, because with `update` method checks the length of the array so that we can not pass an empty array.

I will try to implement this method.  But only the lines displayed on the screen can be cleared. The part of the stream that has already been scrolled up cannot be changed.

**Comment by cenk1cenk2** [comment]
Yeah, I know about that limitation, but it would be great if you can make the `clear` method public for me. Very grateful, thank you beforehand.

**Comment by keindev** [comment]
@cenk1cenk2 see [erase](https://github.com/keindev/stdout-update/blob/master/docs/api/classes/updatemanager.md#erase). By default erases all lines

**Comment by cenk1cenk2** [comment]
Thank you very much.  I am very grateful. I will give it a go on this weekend hopefully. This is even a better approach in my eyes. Hopefully can implement partial update since it is a bit complicated with current setup.
