### ISSUE TITLE
Node Version change on Minor release

### ISSUE THREAD

**Issue by ComBarnea** [keindev/stdout-update#608]
On version 1.6.6 the Node engine was changed as documented on the release page:
Bumped node from 12.0.0 to 14.0.0

I would consider that a Major release change, as this sort of change does have breaking changes on deployment using traditional ^ updates. 

Please consider updating that engine update to version ^2.*.* and release another version 1.6.8 with version 12.0.0 for Node engine.

**Comment by keindev** [comment]
Fixed in v1.6.8, thanks for pointing out my bug.
